// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANzeaMrF9_d2yrQnXenoqxPzMsqpXScZI',
    appId: '1:594449763313:web:312f78abdb429021255250',
    messagingSenderId: '594449763313',
    projectId: 'stocklakriraa',
    authDomain: 'stocklakriraa.firebaseapp.com',
    databaseURL: 'https://stocklakriraa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stocklakriraa.firebasestorage.app',
    measurementId: 'G-Z7H812W3HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8W_tFynnA1GeZYNFH8V5XOsKFTB4zyA',
    appId: '1:594449763313:android:1c6b6153abad2166255250',
    messagingSenderId: '594449763313',
    projectId: 'stocklakriraa',
    databaseURL: 'https://stocklakriraa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stocklakriraa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAprMJi7Lba2kYqGrfEqNFe7lYYzfJAHEU',
    appId: '1:594449763313:ios:275bc2e9fd72379f255250',
    messagingSenderId: '594449763313',
    projectId: 'stocklakriraa',
    databaseURL: 'https://stocklakriraa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stocklakriraa.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAprMJi7Lba2kYqGrfEqNFe7lYYzfJAHEU',
    appId: '1:594449763313:ios:275bc2e9fd72379f255250',
    messagingSenderId: '594449763313',
    projectId: 'stocklakriraa',
    databaseURL: 'https://stocklakriraa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stocklakriraa.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANzeaMrF9_d2yrQnXenoqxPzMsqpXScZI',
    appId: '1:594449763313:web:21bda8a4aa36e399255250',
    messagingSenderId: '594449763313',
    projectId: 'stocklakriraa',
    authDomain: 'stocklakriraa.firebaseapp.com',
    databaseURL: 'https://stocklakriraa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'stocklakriraa.firebasestorage.app',
    measurementId: 'G-V2G1SZ9ZXN',
  );
}
